# request permanent storage for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: finance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi