# minikube api version for mysql secret
apiVersion: v1
# types of resources
kind: Secret
# metadata = information about the secret
metadata:
  # name of the secret
  name: mysql-secret
  namespace: finance
# type of secret
type: Opaque # Opaque means that the secret is a generic secret that can hold any type of data, such as passwords, tokens, or keys.
stringData:
  # key-value pairs of the secret data
  # mysql root password
  MYSQL_ROOT_PASSWORD: Mainali2580#
  # mysql normal user passsword
  MYSQL_PASSWORD: DEMO123#